### PR TITLE
fixed unicode URI decoding

### PR DESCRIPTION
**Pull request by olydis**
- added reproing test case
- fixed issue #5

### CODE REVIEW

**Comment by TooTallNate** [comment]
Thanks!

**Comment by olydis** [comment]
@TooTallNate any chance you could republish the package such that [this](https://github.com/TooTallNate/node-get-uri/blob/master/package.json) picks it up?

**Comment by TooTallNate** [comment]
@olydis Ya, see v1.0.0

**Comment by olydis** [comment]
Thank you! 🎉

**Pull request merged**
